name-template: "v$RESOLVED_VERSION"
tag-template:  "v$RESOLVED_VERSION"

categories:
  - title: "✨ Features"     ; labels: ["feat","enhancement","AI"]
  - title: "🐛 Fixes"        ; labels: ["fix","bug"]
  - title: "🧹 Chores / CI"  ; labels: ["chore","docs","ci","build","test","design"]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## Changes
  $CHANGES

autolabeler:
  - label: "feat" ; title: ["/^feat/i"]
  - label: "fix"  ; title: ["/^fix/i"]

version-resolver:
  major: { labels: ["breaking"] }
  minor: { labels: ["feat","enhancement","AI"] }
  patch: { labels: ["fix","bug","chore","docs","ci","build","test","design"] }

exclude-labels: ["skip-changelog"]
