name: Release Drafter
permissions:
  contents: write
  pull-requests: read
on:
  push:        { branches: [ main ] }
  pull_request:{ types: [opened, reopened, synchronize, ready_for_review, closed] }
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        with: { config-name: release-drafter.yml }
